---
# Main postgresql tasks file

- ansible.builtin.include_tasks: postgresql-ubuntu.yml
  when: ansible_os_family == "Debian"
- ansible.builtin.include_tasks: postgresql-archlinux.yml
  when: ansible_os_family == "Archlinux"
- ansible.builtin.include_tasks: postgresql-redhat.yml
  when: ansible_os_family == "RedHat"
