---
# Main postgresql tasks file

- include: postgresql-ubuntu.yml
  when: ansible_os_family == "Debian"
- include: postgresql-archlinux.yml
  when: ansible_os_family == "Archlinux"
- include: postgresql-redhat.yml
  when: ansible_os_family == "RedHat"
